<Project>
	<PropertyGroup>
		<PubDir>$([System.IO.Path]::GetFullPath('..\ProductionBuild\'))</PubDir>
		<TaskDll>..\RE.BuildTask\bin\RE.BuildTask.dll</TaskDll>

		<GenerateEditorExecutable>True</GenerateEditorExecutable>

	</PropertyGroup>

	<UsingTask TaskName="RE.BuildTask.EngineBuildTask" AssemblyFile="$(TaskDll)" />

	<Import Project="../BuildTargets/RE.Common.targets" />

	<Target Name="BuildAll">

		<MSBuild Projects="../RE.Launcher.Game/RE.Launcher.Game.csproj" Targets="Publish"
		         Properties=" 
				 ApplicationIcon=$(ApplicationIcon);
				 InformationalVersion=$(Version);
				 RuntimeIdentifier=win-x64;
				 PublishSingleFile=True;
				 Configuration=Production;
				 PublishDir=$(PubDir)" />

		<MSBuild Condition="'$(GenerateEditorExecutable)' == 'True'" Projects="../RE.Launcher.Editor/RE.Launcher.Editor.csproj" Targets="Publish"
		         Properties=" 
				 ApplicationIcon=../editor.ico;
				 InformationalVersion=$(Version);
				 RuntimeIdentifier=win-x64;
				 PublishSingleFile=True;
				 Configuration=Production;
				 PublishDir=$(PubDir)" />
		<EngineBuildTask
			AssetsFolder="$(PubDir)Assets"
			OutputFolder="$(PubDir)paks"
			CompressAssets="true"
			GenerateZip="true"
			Version="$(Version)" />

	</Target>
</Project>