<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<AssemblyName>RunEditor</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RE\RE.csproj" />
	</ItemGroup>

</Project>
