<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType Condition="'$(Configuration)'=='Debug'">Exe</OutputType>
		<OutputType Condition="'$(Configuration)'!='Debug'">Library</OutputType>

		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>True</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<Configurations>Debug;Release;Production</Configurations>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Platforms>AnyCPU;x64</Platforms>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<NoWarn>NU1701;NU1702;NU1510;CS1591</NoWarn>
		<Company>CMDEV</Company>
	</PropertyGroup>

	<Target Name="AddGitCommitHash" BeforeTargets="CoreGenerateAssemblyInfo">
		<Exec Command="git rev-parse HEAD" ConsoleToMSBuild="true" ContinueOnError="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="GitCommitHash" />
		</Exec>

		<ItemGroup>
			<AssemblyAttribute Include="RE.Utils.GitCommitAttribute">
				<_Parameter1>$(GitCommitHash)</_Parameter1>
			</AssemblyAttribute>
		</ItemGroup>
		<ItemGroup>
			<AssemblyAttribute Include="RE.Utils.BuildDateAttribute">
				<_Parameter1>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</_Parameter1>
			</AssemblyAttribute>
		</ItemGroup>

	</Target>

	<Import Project="..\BuildTargets\RE.Common.targets" /> 
	<Import Project="..\BuildTargets\RE.Publish.targets" Condition="'$(Configuration)'=='Production'" />

	<ItemGroup>
		<Compile Remove="Assets\GenerateStaticModel.cs" />
		<Folder Include="Core\World\Ai\" />

		<Resource Include="Assets\RealEngine.ico" />

		<PackageReference Include="AssimpNet" Version="4.1.0" />
		<PackageReference Include="BulletSharp" Version="0.11.1" />
		<PackageReference Include="DotRecast.Core" Version="2026.1.1" />
		<PackageReference Include="DotRecast.Detour" Version="2026.1.1" />
		<PackageReference Include="DotRecast.Recast" Version="2026.1.1" />
		<PackageReference Include="DotRecast.Recast.Toolset" Version="2026.1.1" />
		<PackageReference Include="FmodAudio" Version="2.2.5" Condition="False" />
		<PackageReference Include="freetype" Version="2.8.0.1" />
		<PackageReference Include="Hexa.NET.GLFW" Version="1.0.5" />
		<PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
		<PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
		<PackageReference Include="Hexa.NET.ImGui.Backends.GLFW" Version="1.0.18" />
		<PackageReference Include="Hexa.NET.ImGuizmo" Version="2.2.9" />
		<PackageReference Include="Hexa.NET.ImNodes" Version="2.2.9" />
		<PackageReference Include="Hexa.NET.ImPlot" Version="2.2.9" />
		<PackageReference Include="Hexa.NET.OpenGL4" Version="1.1.0" />
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
		<PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
		<!-- <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" /> -->
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="RenderdocSharp" Version="1.0.0-rc.1" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File.GzArchive" Version="1.1.10" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
		<PackageReference Include="SpaceWizards.SharpFont" Version="1.0.2" />
		<PackageReference Include="StbImageSharp" Version="2.30.15" />
		<PackageReference Include="System.CommandLine" Version="2.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.1" />

		<None Include="Assets\**; Engine\**;">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RE.Fmod\RE.Fmod.csproj" />
	</ItemGroup>
 
</Project>
