<Project> 
	<PropertyGroup>
		<ExeName>RE-Demo-App</ExeName>
		<Version>0.1+dev</Version>
		<ApplicationIcon>../RealEngine.ico</ApplicationIcon>
		<Title>Real Engine</Title>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Authors>DimucaTheDev</Authors>
		<Company>LEFT2.DEV</Company>
		<Product>Real Engine</Product>
		<NoWarn>CS1591</NoWarn>
		<PackageProjectUrl>https://github.com/DimucaTheDev/RealEngine</PackageProjectUrl>
		<Description>REAL Engine!!!!!! A replacement for Unreal Engine 7</Description>
	</PropertyGroup>
</Project>