<Project>
	<PropertyGroup>
		<PubDir>$([System.IO.Path]::GetFullPath('ProductionBuild\'))</PubDir>
		<TaskDll>..\RE.BuildTask\bin\RE.BuildTask.dll</TaskDll>
		<GenerateEditorExecutable>False <!-- Use -e arg instead --></GenerateEditorExecutable>
		<DefineConstants>$(DefineConstants);PROD;PRODUCTION</DefineConstants>
		<Optimize>True</Optimize>
	</PropertyGroup>
	<UsingTask TaskName="RE.BuildTask.EngineBuildTask" AssemblyFile="$(TaskDll)" />
	<Import Project="RE.Common.targets" />
	<Target Name="BuildAll">
		<MSBuild Projects="../RE.BuildTask/RE.BuildTask.csproj" Targets="Restore;Build" />
		<MSBuild Projects="../RE.Launcher.Game/RE.Launcher.Game.csproj" Targets="Restore;Publish" Properties="ApplicationIcon=$(ApplicationIcon);InformationalVersion=$(Version);RuntimeIdentifier=win-x64;PublishSingleFile=True;Configuration=Production;PublishDir=$(PubDir)" />
		<MSBuild Condition="'$(GenerateEditorExecutable)' == 'True'" Projects="../RE.Launcher.Editor/RE.Launcher.Editor.csproj" Targets="Restore;Publish" Properties="ApplicationIcon=../editor.ico;InformationalVersion=$(Version);RuntimeIdentifier=win-x64;PublishSingleFile=True;Configuration=Production;PublishDir=$(PubDir)" />
		<EngineBuildTask AssetsFolder="$(PubDir)Assets" PakOutputFolder="$(PubDir)Engine/Paks" CompressAssets="true" GenerateZip="false" Version="$(Version)" />
	</Target>
</Project>