using BulletSharp;
using BulletSharp.Math;
using OpenTK.Graphics.OpenGL4;
using RE.Debug;
using RE.Utils;
using Vector4 = OpenTK.Mathematics.Vector4;

namespace RE.Core.World.Components.Physics
{
    /// <summary>
    /// Provides an OpenTK-based implementation of the BulletSharp.DebugDraw interface for visualizing physics debug
    /// information in a 3D scene.
    /// </summary>
    /// <remarks>Use this class to render debug lines and shapes generated by the Bullet physics engine during
    /// simulation. The debug output can be customized using the static Mode and Xray properties. This class is
    /// typically used for development and debugging purposes to visualize collision shapes, contact points, and other
    /// physics-related data.</remarks>
    public class BulletDebugDrawer : DebugDraw
    {
        public static DebugDrawModes Mode = DebugDrawModes.None;

        public override DebugDrawModes DebugMode { get => Mode; set => Mode = value; }
        public static bool Xray { get; set; }

        public override void DrawLine(ref Vector3 from, ref Vector3 to, ref Vector3 color)
        {
            if (Xray)
                GL.Disable(EnableCap.DepthTest);
            var c = new Vector4(color.X, color.Y, color.Z, 1);
            LineRenderer.DrawLine(from.ToOpenTkVector3(), to.ToOpenTkVector3(), c, c);
            GL.Enable(EnableCap.DepthTest);
        }

        public override void Draw3DText(ref Vector3 location, string textString)
        {
            throw new NotImplementedException();
        }

        public override void ReportErrorWarning(string warningString)
        {
            throw new NotImplementedException();
        }

    }
}
